source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLKAutoLayoutSwift_Example', :exclusive => true do
  pod 'FLKAutoLayoutSwift', :path => '../'
end

target 'FLKAutoLayoutSwift_Tests', :exclusive => true do
  pod 'FLKAutoLayoutSwift', :path => '../'

  
end
